# fly.toml file generated for the-golf-exchange on 2023-04-14T16:58:55Z

app = "the-golf-exchange"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ord"
processes = []

[build]
  image = "flyio/hellofly:latest"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
