databases:
  - name: thegolfexchange 
    plan: free
    databaseName: thegolfexchange
    user: thegolfexchange

services:
  - type: web
    name: thegolfexchange
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: thegolfexchange
          property: connectionString
      - key: abb03cc12184776b9d14262f29d79414
        sync: false
